set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_rx_data[1]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[0]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[2]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[11]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[19]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[3]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[27]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[22]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[24]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[4]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[5]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[12]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[18]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[25]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[13]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[16]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[17]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[6]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[7]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[8]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[14]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[28]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[15]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[23]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[9]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[20]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[21]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[10]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[26]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[29]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[30]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[31]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_rx_ctl[0]}]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/phy_rx_valid]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/phy_tx_ready]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_gearbox_slip]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_data[14]} {u_eth_10g/u_mac_pcs/xver_tx_data[15]} {u_eth_10g/u_mac_pcs/xver_tx_data[16]} {u_eth_10g/u_mac_pcs/xver_tx_data[17]} {u_eth_10g/u_mac_pcs/xver_tx_data[1]} {u_eth_10g/u_mac_pcs/xver_tx_data[0]} {u_eth_10g/u_mac_pcs/xver_tx_data[13]} {u_eth_10g/u_mac_pcs/xver_tx_data[11]} {u_eth_10g/u_mac_pcs/xver_tx_data[12]} {u_eth_10g/u_mac_pcs/xver_tx_data[2]} {u_eth_10g/u_mac_pcs/xver_tx_data[3]} {u_eth_10g/u_mac_pcs/xver_tx_data[4]} {u_eth_10g/u_mac_pcs/xver_tx_data[5]} {u_eth_10g/u_mac_pcs/xver_tx_data[6]} {u_eth_10g/u_mac_pcs/xver_tx_data[7]} {u_eth_10g/u_mac_pcs/xver_tx_data[8]} {u_eth_10g/u_mac_pcs/xver_tx_data[9]} {u_eth_10g/u_mac_pcs/xver_tx_data[10]} {u_eth_10g/u_mac_pcs/xver_tx_data[28]} {u_eth_10g/u_mac_pcs/xver_tx_data[29]} {u_eth_10g/u_mac_pcs/xver_tx_data[30]} {u_eth_10g/u_mac_pcs/xver_tx_data[31]} {u_eth_10g/u_mac_pcs/xver_tx_data[18]} {u_eth_10g/u_mac_pcs/xver_tx_data[19]} {u_eth_10g/u_mac_pcs/xver_tx_data[20]} {u_eth_10g/u_mac_pcs/xver_tx_data[21]} {u_eth_10g/u_mac_pcs/xver_tx_data[27]} {u_eth_10g/u_mac_pcs/xver_tx_data[22]} {u_eth_10g/u_mac_pcs/xver_tx_data[23]} {u_eth_10g/u_mac_pcs/xver_tx_data[24]} {u_eth_10g/u_mac_pcs/xver_tx_data[25]} {u_eth_10g/u_mac_pcs/xver_tx_data[26]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[0]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[1]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[2]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[3]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[4]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[5]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_header[0]} {u_eth_10g/u_mac_pcs/xver_tx_header[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xver_rx_data[0]} {u_eth_10g/u_mac_pcs/xver_rx_data[1]} {u_eth_10g/u_mac_pcs/xver_rx_data[2]} {u_eth_10g/u_mac_pcs/xver_rx_data[3]} {u_eth_10g/u_mac_pcs/xver_rx_data[4]} {u_eth_10g/u_mac_pcs/xver_rx_data[5]} {u_eth_10g/u_mac_pcs/xver_rx_data[6]} {u_eth_10g/u_mac_pcs/xver_rx_data[7]} {u_eth_10g/u_mac_pcs/xver_rx_data[8]} {u_eth_10g/u_mac_pcs/xver_rx_data[9]} {u_eth_10g/u_mac_pcs/xver_rx_data[11]} {u_eth_10g/u_mac_pcs/xver_rx_data[10]} {u_eth_10g/u_mac_pcs/xver_rx_data[26]} {u_eth_10g/u_mac_pcs/xver_rx_data[27]} {u_eth_10g/u_mac_pcs/xver_rx_data[28]} {u_eth_10g/u_mac_pcs/xver_rx_data[29]} {u_eth_10g/u_mac_pcs/xver_rx_data[30]} {u_eth_10g/u_mac_pcs/xver_rx_data[31]} {u_eth_10g/u_mac_pcs/xver_rx_data[13]} {u_eth_10g/u_mac_pcs/xver_rx_data[12]} {u_eth_10g/u_mac_pcs/xver_rx_data[14]} {u_eth_10g/u_mac_pcs/xver_rx_data[21]} {u_eth_10g/u_mac_pcs/xver_rx_data[15]} {u_eth_10g/u_mac_pcs/xver_rx_data[25]} {u_eth_10g/u_mac_pcs/xver_rx_data[16]} {u_eth_10g/u_mac_pcs/xver_rx_data[17]} {u_eth_10g/u_mac_pcs/xver_rx_data[22]} {u_eth_10g/u_mac_pcs/xver_rx_data[18]} {u_eth_10g/u_mac_pcs/xver_rx_data[19]} {u_eth_10g/u_mac_pcs/xver_rx_data[24]} {u_eth_10g/u_mac_pcs/xver_rx_data[20]} {u_eth_10g/u_mac_pcs/xver_rx_data[23]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_tx_data[26]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[27]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[28]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[29]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[30]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[31]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[0]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[11]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[3]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[1]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[2]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[4]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[5]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[24]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[6]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[7]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[8]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[14]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[25]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[15]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[16]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[22]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[19]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[21]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[23]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[17]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[18]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[20]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[13]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[9]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[12]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[10]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[0]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[1]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[2]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[3]}]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_data_valid]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_header_valid]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/xver_rx_header[0]} {u_eth_10g/u_mac_pcs/xver_rx_header[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[0]} {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[1]} {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[2]}]]
set_property mark_debug true [get_nets {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtwiz_userdata_tx_in[*]} ]
set_property mark_debug true [get_nets {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtwiz_userdata_rx_out[*]}]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxdatavalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxdatavalid_out[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxheadervalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxheadervalid_out[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[1]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[2]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[4]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[5]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[3]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxdatavalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxdatavalid_out[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txheader_in[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txheader_in[1]}]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[1]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[2]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[3]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[4]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[5]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[6]}]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/rx_state]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/rx_next_state]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/phy_rx_valid]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/sfd_found]]
set_property mark_debug true [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/sfd_found_del]]
set_property mark_debug true [get_nets [list {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[0]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[1]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[2]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[3]}]]
set_property mark_debug true [get_nets [list u_eth_10g/mac_pcs_rx_reset]]
set_property mark_debug true [get_nets [list u_eth_10g/gtwiz_rx_ready]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/rx_ready]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_reset_rx_done_int]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_buffbypass_rx_done_int]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_buffbypass_rx_reset_int]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/hb_gtwiz_reset_all_int]]
set_property mark_debug true [get_nets [list u_eth_10g/u_gtwizard_wrapper/hb0_gtwiz_userclk_rx_reset_int]]

create_debug_core u_ila_0 ila
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
create_debug_core u_ila_1 ila
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
connect_debug_port u_ila_0/clk [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_rx_user_clocking_internal.gen_single_instance.gtwiz_userclk_rx_inst/gtwiz_userclk_rx_usrclk2_out[0]} ]]
connect_debug_port u_ila_1/clk [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_tx_user_clocking_internal.gen_single_instance.gtwiz_userclk_tx_inst/gtwiz_userclk_tx_usrclk2_out[0]} ]]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxdatavalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxdatavalid_out[1]} ]]
create_debug_port u_ila_0 probe
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxheadervalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxheadervalid_out[1]} ]]
create_debug_port u_ila_0 probe
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxdatavalid_out[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/rxdatavalid_out[1]} ]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[0]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[1]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[2]} {u_eth_10g/u_mac_pcs/u_mac/u_rx/term_loc[3]} ]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_rx_data[0]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[1]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[2]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[3]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[4]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[5]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[6]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[7]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[8]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[9]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[10]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[11]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[12]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[13]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[14]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[15]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[16]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[17]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[18]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[19]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[20]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[21]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[22]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[23]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[24]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[25]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[26]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[27]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[28]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[29]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[30]} {u_eth_10g/u_mac_pcs/xgmii_rx_data[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_rx_ctl[0]} {u_eth_10g/u_mac_pcs/xgmii_rx_ctl[1]} {u_eth_10g/u_mac_pcs/xgmii_rx_ctl[2]} {u_eth_10g/u_mac_pcs/xgmii_rx_ctl[3]} ]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_eth_10g/u_mac_pcs/xver_rx_data[0]} {u_eth_10g/u_mac_pcs/xver_rx_data[1]} {u_eth_10g/u_mac_pcs/xver_rx_data[2]} {u_eth_10g/u_mac_pcs/xver_rx_data[3]} {u_eth_10g/u_mac_pcs/xver_rx_data[4]} {u_eth_10g/u_mac_pcs/xver_rx_data[5]} {u_eth_10g/u_mac_pcs/xver_rx_data[6]} {u_eth_10g/u_mac_pcs/xver_rx_data[7]} {u_eth_10g/u_mac_pcs/xver_rx_data[8]} {u_eth_10g/u_mac_pcs/xver_rx_data[9]} {u_eth_10g/u_mac_pcs/xver_rx_data[10]} {u_eth_10g/u_mac_pcs/xver_rx_data[11]} {u_eth_10g/u_mac_pcs/xver_rx_data[12]} {u_eth_10g/u_mac_pcs/xver_rx_data[13]} {u_eth_10g/u_mac_pcs/xver_rx_data[14]} {u_eth_10g/u_mac_pcs/xver_rx_data[15]} {u_eth_10g/u_mac_pcs/xver_rx_data[16]} {u_eth_10g/u_mac_pcs/xver_rx_data[17]} {u_eth_10g/u_mac_pcs/xver_rx_data[18]} {u_eth_10g/u_mac_pcs/xver_rx_data[19]} {u_eth_10g/u_mac_pcs/xver_rx_data[20]} {u_eth_10g/u_mac_pcs/xver_rx_data[21]} {u_eth_10g/u_mac_pcs/xver_rx_data[22]} {u_eth_10g/u_mac_pcs/xver_rx_data[23]} {u_eth_10g/u_mac_pcs/xver_rx_data[24]} {u_eth_10g/u_mac_pcs/xver_rx_data[25]} {u_eth_10g/u_mac_pcs/xver_rx_data[26]} {u_eth_10g/u_mac_pcs/xver_rx_data[27]} {u_eth_10g/u_mac_pcs/xver_rx_data[28]} {u_eth_10g/u_mac_pcs/xver_rx_data[29]} {u_eth_10g/u_mac_pcs/xver_rx_data[30]} {u_eth_10g/u_mac_pcs/xver_rx_data[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_eth_10g/u_mac_pcs/xver_rx_header[0]} {u_eth_10g/u_mac_pcs/xver_rx_header[1]} ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_buffbypass_rx_done_int ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_buffbypass_rx_reset_int ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list u_eth_10g/u_gtwizard_wrapper/gtwiz_reset_rx_done_int ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list u_eth_10g/gtwiz_rx_ready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list u_eth_10g/u_gtwizard_wrapper/hb0_gtwiz_userclk_rx_reset_int ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list u_eth_10g/mac_pcs_rx_reset ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list u_eth_10g/u_mac_pcs/phy_rx_valid ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/rx_next_state ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list u_eth_10g/u_gtwizard_wrapper/rx_ready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/rx_state ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/sfd_found ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list u_eth_10g/u_mac_pcs/u_mac/u_rx/sfd_found_del ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_data_valid ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_gearbox_slip ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list u_eth_10g/u_mac_pcs/xver_rx_header_valid ]]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[0]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[1]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[2]} {u_eth_10g/u_mac_pcs/xgmii_tx_ctl[3]} ]]
create_debug_port u_ila_1 probe
set_property port_width 7 [get_debug_ports u_ila_1/probe1]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[0]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[1]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[2]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[3]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[4]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[5]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/txsequence_in[6]} ]]
create_debug_port u_ila_1 probe
set_property port_width 4 [get_debug_ports u_ila_1/probe2]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[2]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[3]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[4]} {u_eth_10g/u_gtwizard_wrapper/example_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[3].gen_enabled_channel.gtye4_channel_wrapper_inst/rxheader_out[5]} ]]
create_debug_port u_ila_1 probe
set_property port_width 6 [get_debug_ports u_ila_1/probe3]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[0]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[1]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[2]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[3]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[4]} {u_eth_10g/u_mac_pcs/xver_tx_gearbox_sequence[5]} ]]
create_debug_port u_ila_1 probe
set_property port_width 2 [get_debug_ports u_ila_1/probe4]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_header[0]} {u_eth_10g/u_mac_pcs/xver_tx_header[1]} ]]
create_debug_port u_ila_1 probe
set_property port_width 32 [get_debug_ports u_ila_1/probe5]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {u_eth_10g/u_mac_pcs/xgmii_tx_data[0]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[1]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[2]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[3]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[4]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[5]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[6]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[7]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[8]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[9]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[10]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[11]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[12]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[13]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[14]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[15]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[16]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[17]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[18]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[19]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[20]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[21]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[22]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[23]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[24]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[25]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[26]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[27]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[28]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[29]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[30]} {u_eth_10g/u_mac_pcs/xgmii_tx_data[31]} ]]
create_debug_port u_ila_1 probe
set_property port_width 32 [get_debug_ports u_ila_1/probe6]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {u_eth_10g/u_mac_pcs/xver_tx_data[0]} {u_eth_10g/u_mac_pcs/xver_tx_data[1]} {u_eth_10g/u_mac_pcs/xver_tx_data[2]} {u_eth_10g/u_mac_pcs/xver_tx_data[3]} {u_eth_10g/u_mac_pcs/xver_tx_data[4]} {u_eth_10g/u_mac_pcs/xver_tx_data[5]} {u_eth_10g/u_mac_pcs/xver_tx_data[6]} {u_eth_10g/u_mac_pcs/xver_tx_data[7]} {u_eth_10g/u_mac_pcs/xver_tx_data[8]} {u_eth_10g/u_mac_pcs/xver_tx_data[9]} {u_eth_10g/u_mac_pcs/xver_tx_data[10]} {u_eth_10g/u_mac_pcs/xver_tx_data[11]} {u_eth_10g/u_mac_pcs/xver_tx_data[12]} {u_eth_10g/u_mac_pcs/xver_tx_data[13]} {u_eth_10g/u_mac_pcs/xver_tx_data[14]} {u_eth_10g/u_mac_pcs/xver_tx_data[15]} {u_eth_10g/u_mac_pcs/xver_tx_data[16]} {u_eth_10g/u_mac_pcs/xver_tx_data[17]} {u_eth_10g/u_mac_pcs/xver_tx_data[18]} {u_eth_10g/u_mac_pcs/xver_tx_data[19]} {u_eth_10g/u_mac_pcs/xver_tx_data[20]} {u_eth_10g/u_mac_pcs/xver_tx_data[21]} {u_eth_10g/u_mac_pcs/xver_tx_data[22]} {u_eth_10g/u_mac_pcs/xver_tx_data[23]} {u_eth_10g/u_mac_pcs/xver_tx_data[24]} {u_eth_10g/u_mac_pcs/xver_tx_data[25]} {u_eth_10g/u_mac_pcs/xver_tx_data[26]} {u_eth_10g/u_mac_pcs/xver_tx_data[27]} {u_eth_10g/u_mac_pcs/xver_tx_data[28]} {u_eth_10g/u_mac_pcs/xver_tx_data[29]} {u_eth_10g/u_mac_pcs/xver_tx_data[30]} {u_eth_10g/u_mac_pcs/xver_tx_data[31]} ]]
create_debug_port u_ila_1 probe
set_property port_width 3 [get_debug_ports u_ila_1/probe7]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[0]} {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[1]} {u_eth_10g/u_mac_pcs/u_mac/u_tx/tx_state[2]} ]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list u_eth_10g/u_gtwizard_wrapper/hb0_gtwiz_userclk_tx_reset_int ]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list u_eth_10g/u_mac_pcs/phy_tx_ready ]]